[package]
name = "frontend_wgpu"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2021"

[dependencies]
chargrid_wgpu = "0.5"
env_logger = "0.11"
app = { path = "../app", features = ["print_stdout"] }
native = { path = "../native" }
