[workspace]

members = [
    "image-to-text",
    "ecs",
    "vector",
    "procgen",
    "rand-range",
    "game",
    "app",
    "native",
    "graphical",
    "ansi-terminal",
    "web",
]

[profile.release]
lto = true
