[workspace]

resolver = "2" # this is required for the wgpu frontend

members = [
    "image-to-text",
    "vector",
    "procgen",
    "rand-range",
    "game",
    "app",
    "native",
    "ansi-terminal",
    "web",
    "ggez",
    "wgpu",
]

[profile.release]
lto = true
