[package]
name = "orbital_decay_ggez"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2021"

[dependencies]
chargrid_ggez = { version = "0.2", features = ["gamepad"] }
env_logger = "0.9"
orbital_decay_app = { path = "../app" }
orbital_decay_native = { path = "../native" }
