[package]
name = "boat_journey_sdl2"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2021"

[dependencies]
chargrid_sdl2 = "0.4"
env_logger = "0.11"
boat_journey_app = { path = "../app" }
boat_journey_native = { path = "../native" }
