[package]
name = "rip_ansi_terminal"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2018"

[dependencies]
env_logger = "0.7"
prototty_ansi_terminal = "0.29"
rip_native = { path = "../native" }
rip_prototty = { path = "../prototty" }
rand = "0.7"
