[package]
name = "procgen"
version = "0.1.0"
authors = ["Stephen Sherratt <stephen@sherra.tt>"]
edition = "2018"

[dependencies]
wfc = "0.10"
grid_2d = "0.15"
rand = "0.8"
direction = "0.18"

[dev-dependencies]
meap = "0.4"
rand_isaac = "0.3"
